development:
  adapter: postgresql
  encoding: unicode
  database: gamestarter-development
  pool: 5
  port: 5432
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: gamestarter-test
  pool: 5
  port: 5432
  host: localhost